---
spring:
  application:
    name: eureka-server-clustered
  profiles: primary
server:
  port: 8011
eureka:
  instance:
    hostname: eureka-primary-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-secondary-server:8012/eureka/,http://eureka-tertiary-server:8013/eureka/

---
spring:
  application:
    name: eureka-server-clustered
  profiles: secondary
server:
  port: 8012
eureka:
  instance:
    hostname: eureka-secondary-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-primary-server:8011/eureka/,http://eureka-tertiary-server:8013/eureka/

---
spring:
  application:
    name: eureka-server-clustered
  profiles: tertiary
server:
  port: 8013
eureka:
  instance:
    hostname: eureka-tertiary-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-primary-server:8011/eureka/,http://eureka-secondary-server:8012/eureka/
